moja-global/community-website

website/.github/ISSUE_TEMPLATE/bug_report.md, website/.github/ISSUE_TEMPLATE/communication-suggestion.md, website/.github/ISSUE_TEMPLATE/documentation-update.md, website/.github/ISSUE_TEMPLATE/feature_request.md, website/.github/ISSUE_TEMPLATE/science-contribution-and-review-.md, website/.github/ISSUE_TEMPLATE/user-feedback.md, website/.github/PULL_REQUEST_TEMPLATE.md
wrt issue no. #3. Added the Issue Templates and PR template.
=> added templates

.github/workflows/auto-labeller.yaml
Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>
Partially_Fixes: #8 
Added needs-triage automatic issue labeller.
[Try it yourself by creating a new issue](https://github.com/Abhishek-kumar09/contributor-website-v2/issues)
=> Added github-issue labeller ci

website/docs/intro.mdx, website/src/components/ContributeCard/index.js, website/src/components/ContributeCard/styles.css, website/src/css/custom.css
This is a generic card which can be used for anything. Currently it will be used for displaying that the page is incomplete and can use new contributors. Fixes #20 
Signed-off-by: sarthakkundra <sarthakkundra21@gmail.com>
=> Created a generic card to be used for displaying info

README.md
Added Vercel's banner to Readme which was a requirement for the sponsorship.
=> added vercel banner

website/docusaurus.config.js
Fixed Logo for The Dark Theme.
Fixes #48 
* Open Hosted Website
* Switch to Dark Mode
* See Navbar Logo
Now, Dark Theme: 
Light Theme ( _Same as Prev._ ) :
...
=> fix: Navbar Logo for Dark Mode

website/src/components/HomepageFeatures.js
Changed the "Write Blogs" text on the homepage.
Fixes  [#21 ]
...
=> Write Blogs changed

.github/workflows/conflicts.yml, .github/workflows/stale.yml, .github/workflows/welcome-first-time-contrib.yml
This PR:
- Adds a Stale bot
- Adds a Merge conflict watcher bot
- Adds a GH Action to welcome new contributors
=> Adding CI pipelines

.github/workflows/welcome-first-time-contrib.yml, website/docusaurus.config.js
=> feat: Add Open Graph image metadata in the docusaurus site of community website

website/docusaurus.config.js, website/static/robots.txt
Signed-off-by: Maku <eemike07@gmail.com>
Fixes sitemap by updating `docusaurus.config.js`.  
Adds `robots.txt` to `static` folder
Since we already have `@docusaurus/preset-classic` installed, we don't need to install `@docusaurus/plugin-sitemap`.  
`@docusaurus/plugin-sitemap` can be configured through `classic preset options`.  
See: https://docusaurus.io/docs/presets#docusauruspreset-classic
Fixes #72 
Honestly, I don't have a real way of testing this until it is fully deployed.
...
=> Fixes sitemap config; Adds robots.txt

website/package-lock.json, website/src/pages/index.module.css
Fixed homepage image on large screens
Fixes #84 
Tested on large screen (1900px)
=> fixed homepage image on large screens

website/docusaurus.config.js
=> Updated Footer

.gitignore, website/community/Support.md, website/community/TSC.md, website/docs/intro.mdx, website/docusaurus.config.js, website/fetchContributors.js, website/package-lock.json, website/package.json, website/sidebarsCommunity.js, website/src/css/custom.css, website/src/pages/index.js
This PR:
- Adds contributor section for the community website
- Adds the search functionality for the community website
- Adds community section for community specific docs
=> Contributors + Community features 

.gitpod.yml, README.md
This PR:
- Adds GitPod App to the repository
- Adds `.gitpod.yml` to the project 
- Adds instruction on README to get started with GitPod development
=> FEAT: Add GitPod integration for the community website

website/src/pages/index.module.css
I have updated the margin of links in the ```hero``` div of the header section.
#100 
The updated links look like this - 
...
=> Updated margin of links in header section

.github/workflows/lint.yml, website/community/Docs-Contributions.md, website/community/Management-Contributions.md, website/community/Mentorship.md, website/community/governance.md, website/docusaurus.config.js, website/sidebarsCommunity.js, website/src/components/CommunityCard/index.js, website/src/components/ContributeCard/index.js, website/src/components/HomepageFeatures.js, website/src/components/PastMeetingCard/index.js, website/src/pages/ProjectCard/ProjectCard.js, website/src/pages/index.js, website/src/pages/initiatives.js, website/src/pages/roadmap.js
This PR:
- Adds Spanish translation doc link on the main page
- Fix Newsletter link
- Add management contribution docs
- Add documentation contribution docs
- Lint the entire codebase
- Add a GHA for automated lint checks
- Add Governance docs
=> Add documentation on the community website

website/README.md
Signed-off-by: SanjaySinghRajpoot <iamsanjayrajpoot@gmail.com>
`community-website/website` doesn't have mentions about Linting Guidelines for the doc site. Now I have added the lining guideline to the website. 
Fixes #178 
=> Added linting Guidelines to community/website README.md

README.md
This PR:
- Adds new relevant information to the `README.md`
=> Revamping the repository `README.md`

README.md
Fixes #238
I have added cd website command in readme.md 
- [yes] Bug fix (non-breaking change which fixes an issue).
=> Added cd website command in readme.md

website/src/pages/ProjectCard/ProjectCard.js, website/src/pages/roadmap.js, website/websiteData/roadmap.js
Fixes #234
Initially when we click on github link it was redirecting us to www.github.com but i have added link to redirect to particular specific repository of the project.
- [yes] Bug fix (non-breaking change which fixes an issue).
Go to https://community.moja.global/roadmap
Scroll down and click on view timeline
Click on github
See error
https://user-images.githubusercontent.com/87171452/145672398-0877e790-60bf-4798-b0be-5d0a252a9f65.mp4
...
=> Added redirect to correct repository link

README.md
Changed the link for Moja Global Logo in the README because it wasn't working.
Manually.
BEFORE:
AFTER:
...
=> Correct Moja Global Logo in README

website/docusaurus.config.js
Added a dropdown(left section of navbar) with Initiatives, Case Studies and Tutorial in it with a title "Know More". Rest of navbar items are unchanged.
Changes are made in docusaurus.config.js file. The motivation for this change was to make the navbar look more free as it looked quite congested earlier. No external dependencies are required to merge these changes.
Fixes #231 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
...
=> Dropdown added

README.md
Removed all grammatical errors for example: working: work, moja: Moja, edication: education, punctuation mistakes, article missing, etc.
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
...
=> Updated Readme, removed several grammatical errors

.github/workflows/update-contributors.yml
This PR fixes the update contributors Github Action. This action is now scheduled to run at 00:00 UTC every Monday.
Fixes #289 
The action has been run locally using the `act`
=> Fixed update contributor action

.github/workflows/update-contributors.yml
The input commit_message to the action EndBug/add-and-commit@v7
Fixes #293 
The action has been tested manually using workflow_dispatch
=> Changed input commit_message to message in action update contributors

website/community/Community-Website-Contributions.md, website/package.json, website/scripts/write-projects.js
This PR adds a script to automatically generate project files. Relevant docs to use the script have also been added.
=> FEAT: Implement a script to automatically generate project files

website/src/css/custom.css
I have decreased the padding in mobile view !
Fixes #320 
just open the homepage.
...
=> improved the contributor stats view in mobile

website/docusaurus.config.js
=> fix: incorrect URL in config file

website/src/pages/index.module.css
fix hero section layout issues
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
...
=> fix: hero section layout issues

website/blog/2022-09-09-gsoc-gcbm-editor-status-report.md, website/blog/authors.yml
Adds the Status Report Blog (Final Evaluation) for GCBM Simulation Editor
Go to /blog/gsoc-gcbm-editor-status-report
...
=> feat: add GSoC Status Report Blog for GCBM Editor

website/blog/2022-09-09-GSoC-2022-Final-Report-Palak-Sharma.md, website/blog/authors.yml
Added a blog describing GSoC 2022 project 
@HarshCasper, may you please once review this pull request :)
=> feat: add GSoC blog report for UI library

website/blog/2022-09-11-GSoC-2022-final-report-Radis-Toumpalidis.md
=> Add staus blog

website/docusaurus.config.js
Signed-off-by: Arya Gupta <arya.gupta99999@gmail.com>
Fixed broken link to FAQs on the home page of community website
Fixes # (https://github.com/moja-global/community-website/issues/384)
=> fix:  fix footer link

website/docusaurus.config.js, website/src/components/ContributeCard/styles.css, website/src/components/HomePageFeatures/HomepageFeatures.module.css
I have made changes in "Working Groups" spelling present in the footer section, along with it I have also fixed the Nav Bar to top and have made the text-alignment to left.
These changes are tested on Windows 11 Google Chrome and Microsoft Edge Platform.
=> fix: spelling error in footer

website/websiteData/features.js
Signed-off-by: Jyotirmoy Roy <jyotirmoyroy649@gmail.com>
Fixed the broken links of the community website under the How To Guides of "Know the community"
Fixes #390 
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
...
=> Fix broken links on on Know the Community section

website/package.json, website/src/components/CommunitySlide/CommunitySlide.css, website/src/components/CommunitySlide/CommunitySlide.module.css, website/src/components/CommunitySlide/index.js, website/src/components/CommunitySlideCarouselSection/index.js, website/src/pages/index.js, website/websiteData/features.js, website/yarn.lock
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
...
=> FEAT: community section revamped
